# @req SCI-HELM-005, SCI-HELM-002
apiVersion: v1
kind: Secret
metadata:
  name: sdd-db-credentials
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  password: {{ "PLACEHOLDER_CHANGE_ME" | b64enc | quote }}
  postgres-password: {{ "PLACEHOLDER_CHANGE_ME" | b64enc | quote }}
